language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e . 
  - pip install -r tests/requirements.txt

script: 
  - pytest --cov levitate --cov-report term-missing

after_success:
  - bash < (curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: converage
    - stage: deploy
      python: "3.6"
      install: 
          - pip install -e . 
          - pip install -r docs/requirements.txt
      script: sphinx-build -M html docs .
      deploy: 
        provider: pages
        skip-cleanup: true
        keep-history: true
        target-branch: gh-pages
        github-token: $GITHUB_TOKEN
        on:
          branch: master

