language: python

install:
  - pip install -e . 
  - pip install -r tests/requirements.txt

script: 
  - pytest

.mixins:
- &xenial-mixin
  dist: xenial
  sudo: true

jobs:
  include:
    - name: "3.4 tests"
      python: "3.4"
    - name: "3.5 tests"
      python: "3.5"
    - name: "3.6 tests, converage"
      python: "3.6"
      script: pytest --cov levitate --cov-report term-missing
      after_success: bash <(curl -s https://codecov.io/bash)
    - name: "3.7"
      <<: *xenial-mixin
    - stage: deploy
      python: "3.6"
      install: 
          - pip install -e . 
          - pip install -r docs/requirements.txt
      script: 
        - sphinx-build -M html docs .
        - echo '<html>\n<head>\n<meta http-equiv="refresh" content="0; url=html/index.html" />\n</head>\n<body></body>\n</html>' > index.html
        - touch .nojekyll
      deploy: 
        provider: pages
        skip-cleanup: true
        keep-history: true
        target-branch: gh-pages
        github-token: $GITHUB_TOKEN
        on:
          branch: master
