language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

script: 
  - pytest --cov levitate --cov-report term-missing

install:
  - pip install -e . 
  - pip install tests/requirements.txt

jobs:
  include:
    - stage: deploy
      python: "3.6"
      install: 
          - pip install -e . 
          - pip install docs/requirements.txt
      script: sphinx-build -M html docs .
      deploy: 
        provider: pages
        skip-cleanup: true
        keep-history: true
        target-branch: gh-pages
        github-token: $GITHUB_TOKEN
        on:
          branch: master

